CREATE TABLE IF NOT EXISTS users (
  uid SERIAL PRIMARY KEY,
  utoken VARCHAR(255) NOT NULL,
  uname VARCHAR(64) NOT NULL,
  usurname VARCHAR(64) NOT NULL,
  upassword VARCHAR(255) NOT NULL,
  ugender VARCHAR(32) NOT NULL,
  uemail VARCHAR(255) NOT NULL,
  uage INT NOT NULL CHECK (uAge >= 16),
  urole VARCHAR(64) DEFAULT 'User',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS offers (
  oid SERIAL PRIMARY KEY,
  ouid INT NOT NULL REFERENCES users(uID) ON DELETE CASCADE,
  oname VARCHAR(64) NOT NULL,
  odescribe VARCHAR(64),
  oprice INT NOT NULL,
  ovalues INT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
