CREATE TABLE IF NOT EXISTS users (
	id SERIAL PRIMARY KEY,
	token VARCHAR(255) NOT NULL,
	name VARCHAR(64) NOT NULL,
	surname VARCHAR(64) NOT NULL,
	password VARCHAR(255) NOT NULL,
	gender VARCHAR(32) NOT NULL,
	email VARCHAR(255) NOT NULL,
	age INT NOT NULL CHECK (age >= 16),
	role VARCHAR(64) DEFAULT 'User',
	balance INT DEFAULT 0,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS offers (
	id SERIAL PRIMARY KEY,
	uid INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	name VARCHAR(64) NOT NULL,
	description VARCHAR(64),
	price INT NOT NULL,
	value INT NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
