CREATE TABLE IF NOT EXISTS users (
    uID INT AUTO_INCREMENT PRIMARY KEY,
    uToken VARCHAR(255) NOT NULL,
    uName VARCHAR(64) NOT NULL,
    uSurname VARCHAR(64) NOT NULL,
    uPassword VARCHAR(255) NOT NULL,
    uGender VARCHAR(32) NOT NULL,
    uEmail VARCHAR(255) NOT NULL,
    uAge INT NOT NULL CHECK (uAge >= 16),
    uRole VARCHAR(64) DEFAULT 'User'
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS offers (
    oID INT AUTO_INCREMENT PRIMARY KEY,
    oUID VARCHAR(32) NOT NULL,
    oName VARCHAR(64) NOT NULL,
    oDescribe VARCHAR(64) DEFAULT NULL,
    oPrice INT NOT NULL,
    oValues INT NOT NULL
) ENGINE=InnoDB;